### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by SnarkBoojum** [sapier/animalmaterials#2]
Hi,

for quite a few files, the license says "You may copy, use, modify or do nearly anything except removing this copyright notice. And of course you are NOT allowed to pretend you have written it."... what is that "nearly anything" about? Can't a license like MIT/Expat be used? The question came up during the review process of my Debian package.

Thanks,

Snark on #debian-games

**Comment by SnarkBoojum** [comment]
Hi,

my package is still stuck out of Debian for this license question : can we settle it?

Thanks,

Snark on #debian-games

**Comment by sapier** [comment]
removed the "nearly" as it's just useless there

**Comment by SnarkBoojum** [comment]
That does it! Thanks!
